# datasets: [nfcorpus, nq, hotpotqa, fiqa, webis-touche2020, dbpedia-entity, scidocs, fever, climate-fever, scifact, mldr]
datasets: [mldr]
encoders: [huggingface, openai]
chunkers: [cluster_chunker, langchain_chunker, sentence_chunker, whole_chunker, word_chunker]

# add hyperparameter configs below for your own chunker
word_chunker_k: [10]
sentence_chunker_k: [1, 3, 5]
cluster_chunker_lamda: [0, 0.25, 0.5, 0.75, 1]
cluster_chunker_max_samples_per_cluster: [null, 1, 3, 5, 10]
langchain_chunker_breakpoint_threshold_amount: [0.1, 0.3, 0.5, 0.7, 0.9]
# YOUR_CHUNKER_HYPERPARAMETER_1: [VALUE1, VALUE2, ...]
# YOUR_CHUNKER_HYPERPARAMETER_2: [VALUE1, VALUE2, ...]