datasets: [bioasq] #nfcorpus, nq, hotpotqa, fiqa, quora, scidocs, msmarco, qasper, ||  mldr, scifact, webis-touche2020, fever, climate-fever conditionalqa
encoders: [huggingface, openai]
chunkers: [cluster_chunker, baseline_chunker, langchain_chunker, dbscan_chunker, sentence_chunker, whole_chunker, word_chunker]

# # SOMETHING'S WRONG WITH CONDITIONALQA: PANDAS ERROR IN group_by_clusters
# datasets: [conditionalqa] #nfcorpus, nq, hotpotqa, fiqa, quora, scidocs, msmarco, qasper, ||  mldr, scifact, webis-touche2020, fever, climate-fever
# encoders: [openai]
# chunkers: [cluster_chunker, baseline_chunker, langchain_chunker, dbscan_chunker, sentence_chunker, whole_chunker, word_chunker]


# add hyperparameter configs below for your own chunker
word_chunker:
  k: [10]

sentence_chunker:
  k: [1, 3, 5, 7, 9]

cluster_chunker:
  lamda: [0, 0.25, 0.5, 0.75, 1]
  max_samples_per_cluster: [null, 3, 5, 7, 9]

dbscan_chunker:
  lamda: [0, 0.25, 0.5, 0.75, 1]
  eps: [0.1, 0.3, 0.5, 0.7, 0.9]
  min_samples: [1, 3, 5, 7, 9]

langchain_chunker:
  breakpoint_threshold_type: [percentile, standard_deviation, interquartile, gradient]
  percentile: [10, 30, 50, 70, 90]
  standard_deviation: [1, 1.5, 2, 2.5, 3]
  interquartile: [0.5, 0.75, 1, 1.25, 1.5]
  gradient: [10, 30, 50, 70, 90]

baseline_chunker:
  breakpoint_threshold_type: [distance, gradient]
  distance: [0.1, 0.3, 0.5, 0.7, 0.9]
  gradient: [0.1, 0.3, 0.5, 0.7, 0.9]

# YOUR_CHUNKER_NAME:
#   YOUR_CHUNKER_HYPERPARAMETER_1: [VALUE1, VALUE2, ...]
#   YOUR_CHUNKER_HYPERPARAMETER_2: [VALUE1, VALUE2, ...]